version: "3"
services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./model_cache:/app/model_cache
      - ./BE/db:/app/db # Mount the DB directory
    environment:
      - DB_PATH=/app/db/voiceRecord.sqlite # Set the Docker-specific path for SQLite
      - COQUI_LICENSE_AGREEMENT=y # Accept the Coqui license agreement automatically (if supported)
